# Table: rules
INSERT INTO auction.roles (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO auction.roles (id, name) VALUES (2, 'ROLE_MODERATOR');
INSERT INTO auction.roles (id, name) VALUES (3, 'ROLE_ADMIN');

# Table: users
INSERT INTO auction.users (id, email, password, username) VALUES (1, 'rs.dev2@mail.ru', '$2a$10$lfN.I0Hjd.kRsIymXFU/VuvaDtR4WqtPTM5uLgTWp.3JqIqC/GDQe', 'rsdev');

# Table user_roles
INSERT INTO auction.user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO auction.user_roles (user_id, role_id) VALUES (2, 1);

# Table: lot
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (1, 258, 386, 'test', '2021-05-01 16:47:46', 1, 'Apple MacBook Air 13'''' 1.8GHz 128GB', 1, '2021-04-30 16:47:43', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (2, 75, 75, 'Reading is Fun! This package includes a 3-month subscription to the kids Book Club, Elephant Books. Here''s How It Works: 1. Select Your Plan Board books perfect for children 0-2, or picture books for kids 2-6. You choose. 2. Receive Your Package Unique books, beautifully packaged, delivered to your reader’s door with a personalized gift note.  3. Start Creating Memories Your gift will contain 2-3 expertly selected, recently published hardcover children’s books destined to become childhood favorites.', '2021-05-05 14:21:57', 0, 'Join The (Book) Club!', 0, '2021-05-03 14:21:50', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (3, 20, 30, 'Isaac Bruce Autographed Rams  Riddell Speed Mini Helmet Beckett Certification WF43387 Certificate of Authenticity witnessed by Beckett. Makes a great gift for any collector or sports fan! Items ship quickly and securely. YOU WILL RECEIVE THE EXACT ITEM SHOWN. PLEASE ASK QUESTIONS BEFORE YOU BUY.   THANK YOU FOR SUPPORTING OUR YOUTH SPORTS PROGRAM', '2021-05-04 14:32:39', 0, 'ISAAC BRUCE SIGNED RAMS SPEED MINI-HELMET (BECKETT CERT)', 0, '2021-05-03 14:32:32', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (4, 50, 55, 'Rudy Ruettiger Signed/Inscribed "Go Irish!" Notre Dame Football. This ball is authenticated by JSA and includes their Tamper-proof Sticker and Certificate of Authenticity.    JSA CERT  WIT077372 YOU WILL RECEIVE THE EXACT ITEM SHOWN. PLEASE ASK QUESTIONS BEFORE YOU BUY.   THANK YOU FOR SUPPORTING OUR YOUTH SPORTS PROGRAM', '2021-05-03 19:43:23', 0, 'RUDY RUETTIGER NOTRE DAME SIGNED FOOTBALL (JSA CERT)', 0, '2021-05-03 14:43:18', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (5, 30, 25, 'The jewelry business has been a Westphal tradition since 1950. Richard''s father John was a watchmaker', '2021-05-03 18:46:10', 0, 'Westphal Jewelers  $50 Gift Certificate', 0, '2021-05-03 14:46:07', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (6, 5, 7, '', '2021-05-04 15:17:30', 0, 'Handcrafted Jewelry, Gold Artisan Wire Earrings', 0, '2021-05-03 15:16:54', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (7, 303, 350, 'Through a partnership with Chyrstyn Fentroy, a first-soloist at Boston Ballet, Rothy''s created a special shoe, called “The Loafer in Daybreak”. This limited edition loafer is inspired by the dedication and hope that goes into being a dancer—reminiscent of early mornings and the moments of possibility right before dawn. Chyrstyn chose Urbanity Dance as the community partner for the launch of this shoe, demonstrating her commitment to elevating dance as a vital art form that empowers communities. The Daybreak Loafer is available in size 7.5 or 9.', '2021-05-05 15:19:20', 0, 'Limited Edition Rothy''s Loafers (Size 7.5 Or 9)', 0, '2021-05-03 15:19:17', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (8, 650, 700, 'Just what you''ve been waiting for--your own Daniel Boone pellet grill.  Great Plains Motorsport has been our go-to retailer, allowing us to purchase the grill at cost and donating the difference between that cost and the retail value.  The new Prime grills just got even better with the same great Prime features PLUS a collapsible front shelf, interior grill light, rotisserie enabled mounting and stronger reinforced grates. Prime models are built even smarter and stronger. 12V direct power design provides better temp control, greater pellet fuel economy and faster startups! With micro-adjustment capability in the variable-speed fan and auger motor, you can maintain more consistent grill temps. With the grill and pellet view windows you can keep an eye on your food without letting your smoke escape and monitor your pellet supply. With a 13.5” peaked lid and 458 sq. in. of grill space this workhorse can cook anything from a dozen racks of ribs to a small whole hog and monitor multiple food temps with dual meat probes. Control and monitor your grill from your couch or on-the-go with GMG Smart Control. Adjust your smoke and grill temp from 150°F to 550°F with 5° increment control. Adjust and monitor your food temp from your phone with the GMG App. Grill smarter, eat better! Kick your taste buds into a new dimension!  ', '2021-05-05 15:20:20', 655, 'Green Mountain Daniel Boone Wifi Pellet Grill', 3, '2021-05-03 15:20:18', 1);
INSERT INTO auction.lot (lot_id, buy_price, currently, description, ends, first_bid, name, number_of_bids, started, seller_id) VALUES (9, 125, 330, 'This doTERRA  basket contains: Hand &amp; Body Lotion Deep Blue Rub A Petal Diffuser An Aroma Clip 8 - 15 ml Bottles of Essential Oil (Lemon, Peppermint, Lavender, Island Mist, Citrus Bloom, Wild Orange, On Guard and Balance) Cuisine Blends Cooking Collection Essential Oils  Founded in 2008, doTERRA was built on the mission of sharing the highest quality essential oils with the world. Having seen for themselves the incredible benefits from using these precious resources, a group of health-care and business professionals set out to make this mission a reality. They formed a company and named it doTERRA, a Latin derivative meaning “Gift of the Earth.”  Their mission is to provide essential oils that appeal to everyone from the novice to the expert and are safe to use. You can contact the donor, Janie Ediger (316-641-5944) for information about ordering additional spa items and essential oils.  ', '2021-05-05 15:21:56', 150, 'Essential Oils Basket', 3, '2021-05-03 15:21:54', 1);

# ------------------------------
